import Head from "next/head";
import FindLayout from "../../components/FindByValue";

const FindTrivia = () => {
  return (
    <>
      <Head>
        <title>Just Facts - Trivia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FindLayout type="trivia" />
    </>
  );
};

export default FindTrivia;
