import Head from "next/head";
import Card from "../../components/Card";
import AutorenewIcon from "@material-ui/icons/Autorenew";
import SearchIcon from "@material-ui/icons/Search";

const Trivia = () => {
  return (
    <>
      <Head>
        <title>Just Facts - Trivia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Choose A Card..</h1>
        <div className="cards">
          <Card
            text="Get Random"
            background="#eee"
            color="#111"
            icon={
              <AutorenewIcon style={{ fontSize: "2.15em", color: "#111" }} />
            }
            route="trivia/random"
          />
          <Card
            text="Find By Number"
            background="#eee"
            color="#111"
            icon={<SearchIcon style={{ fontSize: "2.15em", color: "#111" }} />}
            route="trivia/find"
          />
        </div>
      </main>

      <style jsx>{`
        main {
          height: 100%;
          width: 100%;
          display: flex;
          flex-direction: column;
          justify-content: center;
        }
        h1 {
          text-align: center;
          font-family: "Montserrat", sans-serif;
          font-size: 2.3em;
          font-weight: 600;
          color: #ee7aff;
        }
        .cards {
          display: flex;
          padding: 2em;
          justify-content: center;
          gap: 2.4em;
          flex-wrap: wrap;
        }
      `}</style>
    </>
  );
};

export default Trivia;
